services:
  - type: web
    name: sygla-h2o-backend
    runtime: python
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: sygla-h2obd
          property: connectionString
